### ISSUE TITLE
🐛 Regression around lint rules harness

### ISSUE THREAD

**Issue by ematipico** [rome/tools#1383]
## Environment

There's a regression around the test harness of our lint rules. When an assertions fails for whatever reason, Rome throw an unexpected error instead of showing a correct diagnostic that is supposed to come form the test harness itself.

## Steps To Reproduce

1. change a rule harness file rjson, from valid to invalid or vice-versa
2. run `rome test`

Stacktrace of the error

```bash
 project-rome/@internal/codec-binary-serial/RSERWriterBase.ts:386:8 tests/unhandledRejection  INTERNAL  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  ✖ Don't know how to serialize the object Map [] to RSER

  31. ___R$project$rome$$internal$codec$binary$serial$RSERWriterCounter_ts$default.encodeObject (project-rome/@internal/codec-binary-serial/RSERWriterBase.ts:386:8)
      ⚠ Cannot render frame as project-rome/@internal/codec-binary-serial/RSERWriterBase.ts does not exist
  32. ___R$project$rome$$internal$codec$binary$serial$RSERWriterCounter_ts$default.encodeValue (project-rome/@internal/codec-binary-serial/RSERWriterBase.ts:523:16)
      ⚠ Cannot render frame as project-rome/@internal/codec-binary-serial/RSERWriterBase.ts does not exist
  33. ___R$project$rome$$internal$codec$binary$serial$RSERWriterCounter_ts$default.encodePlainObject (project-rome/@internal/codec-binary-serial/RSERWriterBase.ts:447:8)
      ⚠ Cannot render frame as project-rome/@internal/codec-binary-serial/RSERWriterBase.ts does not exist
  34. ___R$project$rome$$internal$codec$binary$serial$RSERWriterCounter_ts$default.encodeObject (project-rome/@internal/codec-binary-serial/RSERWriterBase.ts:343:15)
      ⚠ Cannot render frame as project-rome/@internal/codec-binary-serial/RSERWriterBase.ts does not exist
  35. ___R$project$rome$$internal$codec$binary$serial$RSERWriterCounter_ts$default.encodeValue (project-rome/@internal/codec-binary-serial/RSERWriterBase.ts:523:16)
      ⚠ Cannot render frame as project-rome/@internal/codec-binary-serial/RSERWriterBase.ts does not exist
  36. ___R$project$rome$$internal$codec$binary$serial$RSERWriterCounter_ts$default.encodePlainObject (project-rome/@internal/codec-binary-serial/RSERWriterBase.ts:447:8)
      ⚠ Cannot render frame as project-rome/@internal/codec-binary-serial/RSERWriterBase.ts does not exist
  37. ___R$project$rome$$internal$codec$binary$serial$RSERWriterCounter_ts$default.encodeObject (project-rome/@internal/codec-binary-serial/RSERWriterBase.ts:343:15)
      ⚠ Cannot render frame as project-rome/@internal/codec-binary-serial/RSERWriterBase.ts does not exist
  38. ___R$project$rome$$internal$codec$binary$serial$RSERWriterCounter_ts$default.encodeValue (project-rome/@internal/codec-binary-serial/RSERWriterBase.ts:523:16)
      ⚠ Cannot render frame as project-rome/@internal/codec-binary-serial/RSERWriterBase.ts does not exist
  39. ___R$project$rome$$internal$codec$binary$serial$RSERWriterCounter_ts$default.encodeArray (project-rome/@internal/codec-binary-serial/RSERWriterBase.ts:168:8)
      ⚠ Cannot render frame as project-rome/@internal/codec-binary-serial/RSERWriterBase.ts does not exist
  40. ___R$project$rome$$internal$codec$binary$serial$RSERWriterCounter_ts$default.encodeObject (project-rome/@internal/codec-binary-serial/RSERWriterBase.ts:334:15)
      ⚠ Cannot render frame as project-rome/@internal/codec-binary-serial/RSERWriterBase.ts does not exist
  41. ___R$project$rome$$internal$codec$binary$serial$RSERWriterCounter_ts$default.encodeValue (project-rome/@internal/codec-binary-serial/RSERWriterBase.ts:523:16)
      ⚠ Cannot render frame as project-rome/@internal/codec-binary-serial/RSERWriterBase.ts does not exist
  42. ___R$project$rome$$internal$codec$binary$serial$RSERWriterCounter_ts$default.encodePlainObject (project-rome/@internal/codec-binary-serial/RSERWriterBase.ts:447:8)
      ⚠ Cannot render frame as project-rome/@internal/codec-binary-serial/RSERWriterBase.ts does not exist
  43. ___R$project$rome$$internal$codec$binary$serial$RSERWriterCounter_ts$default.encodeObject (project-rome/@internal/codec-binary-serial/RSERWriterBase.ts:343:15)
      ⚠ Cannot render frame as project-rome/@internal/codec-binary-serial/RSERWriterBase.ts does not exist
  44. ___R$project$rome$$internal$codec$binary$serial$RSERWriterCounter_ts$default.encodeValue (project-rome/@internal/codec-binary-serial/RSERWriterBase.ts:523:16)
      ⚠ Cannot render frame as project-rome/@internal/codec-binary-serial/RSERWriterBase.ts does not exist
  45. ___R$project$rome$$internal$codec$binary$serial$RSERWriterCounter_ts$default.encodeArray (project-rome/@internal/codec-binary-serial/RSERWriterBase.ts:168:8)
      ⚠ Cannot render frame as project-rome/@internal/codec-binary-serial/RSERWriterBase.ts does not exist
  46. ___R$project$rome$$internal$codec$binary$serial$RSERWriterCounter_ts$default.encodeObject (project-rome/@internal/codec-binary-serial/RSERWriterBase.ts:334:15)
      ⚠ Cannot render frame as project-rome/@internal/codec-binary-serial/RSERWriterBase.ts does not exist
  47. ___R$project$rome$$internal$codec$binary$serial$RSERWriterCounter_ts$default.encodeValue (project-rome/@internal/codec-binary-serial/RSERWriterBase.ts:523:16)
      ⚠ Cannot render frame as project-rome/@internal/codec-binary-serial/RSERWriterBase.ts does not exist
  48. ___R$project$rome$$internal$codec$binary$serial$RSERWriterCounter_ts$default.encodePlainObject (project-rome/@internal/codec-binary-serial/RSERWriterBase.ts:447:8)
      ⚠ Cannot render frame as project-rome/@internal/codec-binary-serial/RSERWriterBase.ts does not exist
  49. ___R$project$rome$$internal$codec$binary$serial$RSERWriterCounter_ts$default.encodeObject (project-rome/@internal/codec-binary-serial/RSERWriterBase.ts:343:15)
      ⚠ Cannot render frame as project-rome/@internal/codec-binary-serial/RSERWriterBase.ts does not exist
  50. ___R$project$rome$$internal$codec$binary$serial$RSERWriterCounter_ts$default.encodeValue (project-rome/@internal/codec-binary-serial/RSERWriterBase.ts:523:16)
      ⚠ Cannot render frame as project-rome/@internal/codec-binary-serial/RSERWriterBase.ts does not exist
  and 30 others...

  ⚠ This diagnostic was derived from an internal Rome error. Potential bug, please report if necessary.

  ⚠ This diagnostic refers to a file that does not exist

(node:39460) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 2)
  at handledRejection (internal/process/promises.js:140:22) generated source location
  at promiseRejectHandler (internal/process/promises.js:102:6) generated source location
  at Promise.then
  at process.then (project-rome/@internal/core/common/FatalErrorHandler.ts:72:11)
  at process.emit (events.js:314:19) generated source location
  at processPromiseRejections (internal/process/promises.js:245:32) generated source location
  at process.processTicksAndRejections (internal/process/task_queues.js:94:31) generated source location

```

## Expected Results

It should show the correct diagnostic.

**Comment by sebmck** [comment]
Fixed in #1384. (Hasn't merged yet but closing this issue now so I don't forget)
