### ISSUE TITLE
🐛 <TITLE> gitlab runner error

### ISSUE THREAD

**Issue by crazyair** [rome/tools#3772]
### Environment information

```block
gitlab runner
```

### What happened?

```bash
$ pnpm install
Lockfile is up-to-date, resolution step is skipped
Progress: resolved 1, reused 0, downloaded 0, added 0
Packages: +1972
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Progress: resolved 1972, reused 0, downloaded 0, added 0
Packages are hard linked from the content-addressable store to the virtual store.
  Content-addressable store is at: /home/www/.pnpm-store/v3
  Virtual store is at:             node_modules/.pnpm
Progress: resolved 1972, reused 188, downloaded 0, added 188
Progress: resolved 1972, reused 712, downloaded 1, added 702
Progress: resolved 1972, reused 1512, downloaded 1, added 1504
Progress: resolved 1972, reused 1967, downloaded 1, added 1967
Progress: resolved 1972, reused 1971, downloaded 1, added 1972, done
.../node_modules/core-js-pure postinstall$ node -e "try{require('./postinstall')}catch(e){}"
.../core-js@3.6.5/node_modules/core-js postinstall$ node -e "try{require('./postinstall')}catch(e){}"
.../core-js@2.6.12/node_modules/core-js postinstall$ node -e "try{require('./postinstall')}catch(e){}"
.../core-js@3.8.2/node_modules/core-js postinstall$ node -e "try{require('./postinstall')}catch(e){}"
.../es5-ext@0.10.61/node_modules/es5-ext postinstall$  node -e "try{require('./_postinstall')}catch(e){}" || exit 0
.../core-js@2.6.12/node_modules/core-js postinstall: Done
.../core-js@3.6.5/node_modules/core-js postinstall: Done
.../node_modules/core-js-pure postinstall: Done
.../esbuild@0.8.57/node_modules/esbuild postinstall$ node install.js
.../esbuild@0.12.15/node_modules/esbuild postinstall$ node install.js
.../es5-ext@0.10.61/node_modules/es5-ext postinstall: Done
.../core-js@3.8.2/node_modules/core-js postinstall: Done
.../esbuild@0.8.57/node_modules/esbuild postinstall: Done
.../esbuild@0.12.15/node_modules/esbuild postinstall: Done
.../.pnpm/rome@10.0.1/node_modules/rome postinstall$ node scripts/postinstall.js
.../.pnpm/rome@10.0.1/node_modules/rome postinstall: /xxx/node_modules/.pnpm/rome@10.0.1/node_modules/rome/scripts/postinstall.js:18
.../.pnpm/rome@10.0.1/node_modules/rome postinstall: const binName = PLATFORMS?.[platform]?.[arch];
.../.pnpm/rome@10.0.1/node_modules/rome postinstall:                           ^
.../.pnpm/rome@10.0.1/node_modules/rome postinstall: SyntaxError: Unexpected token '.'
.../.pnpm/rome@10.0.1/node_modules/rome postinstall:     at wrapSafe (internal/modules/cjs/loader.js:1054:16)
.../.pnpm/rome@10.0.1/node_modules/rome postinstall:     at Module._compile (internal/modules/cjs/loader.js:1102:27)
.../.pnpm/rome@10.0.1/node_modules/rome postinstall:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
.../.pnpm/rome@10.0.1/node_modules/rome postinstall:     at Module.load (internal/modules/cjs/loader.js:986:32)
.../.pnpm/rome@10.0.1/node_modules/rome postinstall:     at Function.Module._load (internal/modules/cjs/loader.js:879:14)
.../.pnpm/rome@10.0.1/node_modules/rome postinstall:     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
.../.pnpm/rome@10.0.1/node_modules/rome postinstall:     at internal/main/run_main_module.js:17:47
.../.pnpm/rome@10.0.1/node_modules/rome postinstall: Failed
 ELIFECYCLE  Command failed with exit code 1.
```

### Expected result

no error

### Code of Conduct

- [X] I agree to follow Rome's Code of Conduct

**Comment by crazyair** [comment]
xx version ？

how see?

**Comment by crazyair** [comment]
![image](https://user-images.githubusercontent.com/7971419/202391208-60982d90-bde0-4ed7-80ab-47f2f98a24c7.png)

**Comment by MichaReiser** [comment]
Hmm, that's odd. [Optional chaining](https://node.green/#ES2020-features-optional-chaining-operator-----) is supported since node 16

**Comment by crazyair** [comment]
How many versions are recommended

**Comment by MichaReiser** [comment]
> How many versions are recommended

Rome supports node version 14 and newer, which is why I'm confused that you're seeing this error. I installed node14 locally to double-check that it works and Rome runs without any problems. 

Would it be possible to share your gitlab workflow or more information how the job is set up?

**Comment by crazyair** [comment]
Whether it is related to the platform

**Comment by ematipico** [comment]
@crazyair could you try again? In `11.0.0` we changed how the postinstall script is installed

**Comment by crazyair** [comment]
```bash
$ pnpm install
Lockfile is up-to-date, resolution step is skipped
Progress: resolved 1, reused 0, downloaded 0, added 0
Packages: +1981
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Progress: resolved 1981, reused 0, downloaded 0, added 0
Packages are hard linked from the content-addressable store to the virtual store.
  Content-addressable store is at: /home/www/.pnpm-store/v3
  Virtual store is at:             node_modules/.pnpm
Progress: resolved 1981, reused 137, downloaded 1, added 133
Progress: resolved 1981, reused 607, downloaded 3, added 609
Progress: resolved 1981, reused 1332, downloaded 3, added 1334
Progress: resolved 1981, reused 1973, downloaded 3, added 1975
Progress: resolved 1981, reused 1978, downloaded 3, added 1981, done
.../core-js@2.6.12/node_modules/core-js postinstall$ node -e "try{require('./postinstall')}catch(e){}"
.../node_modules/core-js-pure postinstall$ node -e "try{require('./postinstall')}catch(e){}"
.../core-js@3.6.5/node_modules/core-js postinstall$ node -e "try{require('./postinstall')}catch(e){}"
.../es5-ext@0.10.61/node_modules/es5-ext postinstall$  node -e "try{require('./_postinstall')}catch(e){}" || exit 0
.../core-js@3.8.2/node_modules/core-js postinstall$ node -e "try{require('./postinstall')}catch(e){}"
.../core-js@2.6.12/node_modules/core-js postinstall: Done
.../node_modules/core-js-pure postinstall: Done
.../core-js@3.6.5/node_modules/core-js postinstall: Done
.../esbuild@0.12.15/node_modules/esbuild postinstall$ node install.js
.../esbuild@0.8.57/node_modules/esbuild postinstall$ node install.js
.../core-js@3.8.2/node_modules/core-js postinstall: Done
.../es5-ext@0.10.61/node_modules/es5-ext postinstall: Done
.../esbuild@0.12.15/node_modules/esbuild postinstall: Done
.../esbuild@0.8.57/node_modules/esbuild postinstall: Done
.../.pnpm/rome@11.0.0/node_modules/rome postinstall$ node scripts/postinstall.js
.../.pnpm/rome@11.0.0/node_modules/rome postinstall: const binName = PLATFORMS?.[platform]?.[arch];
.../.pnpm/rome@11.0.0/node_modules/rome postinstall:                           ^
.../.pnpm/rome@11.0.0/node_modules/rome postinstall: SyntaxError: Unexpected token '.'
.../.pnpm/rome@11.0.0/node_modules/rome postinstall:     at wrapSafe (internal/modules/cjs/loader.js:1054:16)
.../.pnpm/rome@11.0.0/node_modules/rome postinstall:     at Module._compile (internal/modules/cjs/loader.js:1102:27)
.../.pnpm/rome@11.0.0/node_modules/rome postinstall:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
.../.pnpm/rome@11.0.0/node_modules/rome postinstall:     at Module.load (internal/modules/cjs/loader.js:986:32)
.../.pnpm/rome@11.0.0/node_modules/rome postinstall:     at Function.Module._load (internal/modules/cjs/loader.js:879:14)
.../.pnpm/rome@11.0.0/node_modules/rome postinstall:     at internal/main/run_main_module.js:17:47
.../.pnpm/rome@11.0.0/node_modules/rome postinstall: Failed
 ELIFECYCLE  Command failed with exit code 1.

```

**Comment by ematipico** [comment]
Most probably the issue is around gitlab and its node version. Unfortunately we can't fix it
