### ISSUE TITLE
🐛 Rome client: couldn't create connection to server.

### ISSUE THREAD

**Issue by dayblox** [rome/tools#4374]
### Environment information

```block
Unable to run any `rome` command (including `rome rage`), it always results in:
- error code 127 
- `C:/Users/XXXXXXX/AppData/Local/pnpm/node.exe: error while loading shared libraries: ?: cannot open shared object file: No such file or directory`

VSCode

Version: 1.78.0-insider (user setup)
Commit: 3ad5774eb8123d4224eb55629df9e5f82fe13b99
Date: 2023-04-14T05:25:56.476Z
Electron: 22.4.5
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: Yes

Rome

Extension: Any version, but here with v0.22.0
CLI: 12.0.0
```

### What happened?

1. Launch VSCode
2. Error notification "Rome client: couldn't create connection to server." and following error
```
[cli-stdout] end
[cli-stderr] end
[cli-stderr] close
[cli-stdout] close
[cli] exit 3221225781
[cli] close 3221225781
[Error - 8:47:53 AM] Rome client: couldn't create connection to server.
Error: Command "d:\Documents\Projects\node-ts\node_modules\@rometools\cli-win32-x64\rome.exe __print_socket" exited with code 3221225781
	at getSocket (c:\Users\Dayblox\.vscode-insiders\extensions\rome.rome-0.22.0-win32-x64\out\main.js:19174:11)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async createMessageTransports (c:\Users\Dayblox\.vscode-insiders\extensions\rome.rome-0.22.0-win32-x64\out\main.js:19184:16)
	at async LanguageClient2.createConnection (c:\Users\Dayblox\.vscode-insiders\extensions\rome.rome-0.22.0-win32-x64\out\main.js:15294:28)
	at async LanguageClient2.start (c:\Users\Dayblox\.vscode-insiders\extensions\rome.rome-0.22.0-win32-x64\out\main.js:14892:30)
	at async activate (c:\Users\Dayblox\.vscode-insiders\extensions\rome.rome-0.22.0-win32-x64\out\main.js:18982:3)
	at async b.n (c:\Users\Dayblox\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:96:6640)
	at async b.m (c:\Users\Dayblox\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:96:6603)
	at async b.l (c:\Users\Dayblox\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:96:6060)
```
3. Status bar hover displays "Rome encountered a fatal error"
4. Run `Rome: Restart LSP Server` command
5. Error notification "Restarting client failed" and exact same error
```
[Error - 8:48:13 AM] Restarting client failed
Error: Command "d:\Documents\Projects\node-ts\node_modules\@rometools\cli-win32-x64\rome.exe __print_socket" exited with code 3221225781
	at getSocket (c:\Users\Dayblox\.vscode-insiders\extensions\rome.rome-0.22.0-win32-x64\out\main.js:19174:11)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async createMessageTransports (c:\Users\Dayblox\.vscode-insiders\extensions\rome.rome-0.22.0-win32-x64\out\main.js:19184:16)
	at async LanguageClient2.createConnection (c:\Users\Dayblox\.vscode-insiders\extensions\rome.rome-0.22.0-win32-x64\out\main.js:15294:28)
	at async LanguageClient2.start (c:\Users\Dayblox\.vscode-insiders\extensions\rome.rome-0.22.0-win32-x64\out\main.js:14892:30)
	at async activate (c:\Users\Dayblox\.vscode-insiders\extensions\rome.rome-0.22.0-win32-x64\out\main.js:18982:3)
	at async b.n (c:\Users\Dayblox\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:96:6640)
	at async b.m (c:\Users\Dayblox\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:96:6603)
	at async b.l (c:\Users\Dayblox\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:96:6060)
```

### Expected result

Successfully connect to server and load.

### Code of Conduct

- [X] I agree to follow Rome's Code of Conduct

**Comment by dayblox** [comment]
## Update

3221225781 seems to be related to a missing DLL.
I tried reinstalling everything (VSCode, etc) with no luck, so this must be because I am on a clean Windows 11 install.

What DLLs should I install on a new Windows 11 install to make this work?
