### ISSUE TITLE
🐛 Check failure when building in a clean chroot

### ISSUE THREAD

**Issue by alerque** [rome/tools#4548]
### Environment information

```block
I maintain the [AUR recipe](aur.archlinux.org/packages/rome) for `rome` tools. I also built it and host a prebuilt version in my user repository. I'm also considering promoting this to an official Arch Linux package in the [extra] repository.

As part of the build process, I always build in a clean chroot configured with *just* the dependencies named in the package. For Rust projects this typically also means running `cargo test`. For this project specifically I'm running:


cargo test -p rome_cli --frozen --all-features


This worked up through 12.0.0, but all releases since that including 12.1.3 have started failing checks.
```

### What happened?

Test output:

```
failures:

---- commands::check::fs_error_dereferenced_symlink stdout ----
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ Snapshot Summary ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Snapshot file: crates/rome_cli/tests/snapshots/main_commands_check/fs_error_dereferenced_symlink.snap
Snapshot: fs_error_dereferenced_symlink
Source: crates/rome_cli/tests/snap_test.rs:346
────────────────────────────────────────────────────────────────────────────────
Expression: content
────────────────────────────────────────────────────────────────────────────────
-old snapshot
+new results
────────────┬───────────────────────────────────────────────────────────────────
    0     0 │ # Termination Message
    1     1 │
    2     2 │ ```block
    3       │-internalError/io ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
          3 │+/build/rome/src/tools-cli-v12.1.3/.git internalError/fs ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    4     4 │
    5       │-  × No files were processed in the specified paths.
    6       │-
    7       │-
    8       │-
    9       │-```
   10       │-
   11       │-# Emitted Messages
   12       │-
   13       │-```block
   14       │-<TEMP_DIR>/rome_test_broken_symlink/broken_symlink internalError/fs ━━━━━━━━━━━━━━━━━━━━
   15       │-
   16       │-  ! Dereferenced symlink
          5 │+  × Rome couldn't find the VCS folder at the following path: /build/rome/src/tools-cli-v12.1.3/.git
   17     6 │
   18       │-  i Rome encountered a file system entry that is a broken symbolic link: <TEMP_DIR>/rome_test_broken_symlink/broken_symlink
   19       │-
   20     7 │
   21       │-```
   22     8 │
   23       │-```block
   24       │-Checked 0 file(s) in <TIME>
   25     9 │ ```
   26    10 │
────────────┴───────────────────────────────────────────────────────────────────
To update snapshots run `cargo insta review`
Stopped on the first failure. Run `cargo insta test` to run all snapshots.
thread 'commands::check::fs_error_dereferenced_symlink' panicked at 'snapshot assertion for 'fs_error_dereferenced_symlink' failed in line 346', /build/.cargo/registry/src/github.com-1ecc6299db9ec823/insta-1.28.0/src/runtime.rs:569:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- commands::check::fs_error_infinite_symlink_exapansion stdout ----
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ Snapshot Summary ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Snapshot file: crates/rome_cli/tests/snapshots/main_commands_check/fs_error_infinite_symlink_expansion.snap
Snapshot: fs_error_infinite_symlink_expansion
Source: crates/rome_cli/tests/snap_test.rs:346
────────────────────────────────────────────────────────────────────────────────
Expression: content
────────────────────────────────────────────────────────────────────────────────
-old snapshot
+new results
────────────┬───────────────────────────────────────────────────────────────────
    0     0 │ # Termination Message
    1     1 │
    2     2 │ ```block
    3       │-internalError/io ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    4       │-
    5       │-  × No files were processed in the specified paths.
    6       │-
    7       │-
    8       │-
    9       │-```
   10       │-
   11       │-# Emitted Messages
   12       │-
   13       │-```block
   14       │-<TEMP_DIR>/rome_test_infinite_symlink_exapansion/prefix internalError/fs ━━━━━━━━━━━━━━━━━━━━
          3 │+/build/rome/src/tools-cli-v12.1.3/.git internalError/fs ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
   15     4 │
   16       │-  ! Infinite symlink expansion
          5 │+  × Rome couldn't find the VCS folder at the following path: /build/rome/src/tools-cli-v12.1.3/.git
   17     6 │
   18       │-  × Rome encountered a file system entry that leads to an infinite symbolic link expansion, causing an infinite cycle: <TEMP_DIR>/rome_test_infinite_symlink_exapansion/prefix
   19       │-
   20       │-
   21       │-```
   22     7 │
   23       │-```block
   24       │-<TEMP_DIR>/rome_test_infinite_symlink_exapansion/prefix internalError/fs ━━━━━━━━━━━━━━━━━━━━
   25     8 │
   26       │-  ! Infinite symlink expansion
   27       │-
   28       │-  × Rome encountered a file system entry that leads to an infinite symbolic link expansion, causing an infinite cycle: <TEMP_DIR>/rome_test_infinite_symlink_exapansion/prefix
   29       │-
   30       │-
   31       │-```
   32       │-
   33       │-```block
   34       │-Checked 0 file(s) in <TIME>
   35     9 │ ```
   36    10 │
────────────┴───────────────────────────────────────────────────────────────────
To update snapshots run `cargo insta review`
Stopped on the first failure. Run `cargo insta test` to run all snapshots.
thread 'commands::check::fs_error_infinite_symlink_exapansion' panicked at 'snapshot assertion for 'fs_error_infinite_symlink_expansion' failed in line 346', /build/.cargo/registry/src/github.com-1ecc6299db9ec823/insta-1.28.0/src/runtime.rs:569:9


failures:
    commands::check::fs_error_dereferenced_symlink
    commands::check::fs_error_infinite_symlink_exapansion

test result: FAILED. 143 passed; 2 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.71s
```

### Expected result

Tests should pass even when run in a clean chroot build environment.

### Code of Conduct

- [X] I agree to follow Rome's Code of Conduct

**Comment by ematipico** [comment]
Will look into it, thank you
