### ISSUE TITLE
🐛 LSP Server crashing with `--logs` argument

### ISSUE THREAD

**Issue by yassere** [rome/tools#871]
## Environment

```
$ rome rage --summary
```
<details>
<summary>
Summary
</summary>

```
Environment Variables
  Object {
    COLORTERM: "truecolor"
    LANG: "en_US.UTF-8"
    PATH: "/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/Yasser/bin:/Users/Yasser/bin"
    TERM: "xterm-256color"
    TERM_PROGRAM: "vscode"
    USER: "Yasser"
  }

User Config
  unset

Rome Version
  0.0.26-dev

Node Version
  12.13.0

Platform
  darwin x64 19.5.0

Terminal Features
  Object {
    background: "unknown"
    colorDepth: 8
    columns: 142
    cursor: true
    hyperlinks: true
    isTTY: true
    unicode: true
  }

Client Flags
  Object {
    clientName: "cli"
    cwd: "/Users/Yasser/Dev/rome"
    silent: false
  }

```
</details>

## Steps To Reproduce

Add `"--logs"` to the `args` array [here.](https://github.com/romefrontend/rome/blob/c8e1833a4e5ff75bfa051458626a8502c94f4d16/packages/%40romefrontend-integration/vscode/index.ts#L152)

`./rome run scripts/run-vscode-extension.ts` 

## Expected Results

Should see logs in the VS Code `Rome` output channel as the project's initial lint run is performed, but it shouldn't cause any crashes.

It does show logs, but it crashes and restarts during the process (and then stops restarting after the 5th crash). Here's one example.

<details>
<summary>Crash snippet</summary>

```
[Error: Range end for line index 21 is before the start. end(1) < start(7).
Line content: ""
  at ___R$project$rome$$romefrontend$cli$layout$grid$Grid_ts$default.setRange (project-rome/@romefrontend/cli-layout/grid/Grid.ts:584:9)
  at ___R$project$rome$$romefrontend$cli$layout$grid$Grid_ts$default.addCursorRange (project-rome/@romefrontend/cli-layout/grid/Grid.ts:626:8)
  at ___R$project$rome$$romefrontend$cli$layout$grid$Grid_ts$default.writeText (project-rome/@romefrontend/cli-layout/grid/Grid.ts:574:7)
  at ___R$project$rome$$romefrontend$cli$layout$grid$Grid_ts$default.drawText (project-rome/@romefrontend/cli-layout/grid/Grid.ts:468:7)
  at ___R$project$rome$$romefrontend$cli$layout$grid$Grid_ts$default.drawChild (project-rome/@romefrontend/cli-layout/grid/Grid.ts:1189:8)
  at ___R$project$rome$$romefrontend$cli$layout$grid$Grid_ts$default.drawView (project-rome/@romefrontend/cli-layout/grid/Grid.ts:951:8)
  at ___R$project$rome$$romefrontend$cli$layout$grid$Grid_ts$default.drawTag (project-rome/@romefrontend/cli-layout/grid/Grid.ts:1144:9)
  at ___R$project$rome$$romefrontend$cli$layout$grid$Grid_ts$default.drawChild (project-rome/@romefrontend/cli-layout/grid/Grid.ts:1191:8)
  at ___R$project$rome$$romefrontend$cli$layout$grid$Grid_ts$default.drawView (project-rome/@romefrontend/cli-layout/grid/Grid.ts:951:8)
  at ___R$project$rome$$romefrontend$cli$layout$grid$Grid_ts$default.drawTag (project-rome/@romefrontend/cli-layout/grid/Grid.ts:1144:9)
  at ___R$project$rome$$romefrontend$cli$layout$grid$Grid_ts$default.drawChild (project-rome/@romefrontend/cli-layout/grid/Grid.ts:1191:8)
  at ___R$project$rome$$romefrontend$cli$layout$grid$Grid_ts$default.drawChildren (project-rome/@romefrontend/cli-layout/grid/Grid.ts:1197:8)
  at drawChildren (project-rome/@romefrontend/cli-layout/format.ts:140:6)
  at ___R$project$rome$$romefrontend$cli$layout$format_ts$markupToPlainText (project-rome/@romefrontend/cli-layout/format.ts:151:8)
  at ___R$project$rome$$romefrontend$cli$reporter$Reporter_ts$default.format (project-rome/@romefrontend/cli-reporter/Reporter.ts:876:11)
  at ___R$project$rome$$romefrontend$cli$reporter$Reporter_ts$default.logOne (project-rome/@romefrontend/cli-reporter/Reporter.ts:896:21)
  at ___R$project$rome$$romefrontend$cli$reporter$Reporter_ts$default.logAll (project-rome/@romefrontend/cli-reporter/Reporter.ts:885:8)
  at logAll (project-rome/@romefrontend/cli/cli.ts:500:22)
  at <anonymous> (project-rome/@romefrontend/core/client/Client.ts:318:3)
  at ___R$project$rome$$romefrontend$events$BridgeEvent_ts$default.call (project-rome/@romefrontend/events/Event.ts:106:5)
  at ___R$project$rome$$romefrontend$events$BridgeEvent_ts$default.dispatchRequest (project-rome/@romefrontend/events/BridgeEvent.ts:95:15)
  at ___R$project$rome$$romefrontend$core$common$bridges$ServerBridge_ts$default.handleMessageRequest (project-rome/@romefrontend/events/Bridge.ts:438:16)
  at ___R$project$rome$$romefrontend$core$common$bridges$ServerBridge_ts$default.handleMessage (project-rome/@romefrontend/events/Bridge.ts:394:9)
  at Object.sendMessage (project-rome/@romefrontend/events/bridgeCreators.ts:202:10)
  at ___R$project$rome$$romefrontend$core$common$bridges$ServerBridge_ts$default.sendMessage (project-rome/@romefrontend/events/Bridge.ts:357:7)
  at ___R$project$rome$$romefrontend$events$BridgeEvent_ts$default.send (project-rome/@romefrontend/events/BridgeEvent.ts:148:14)
  at ___R$project$rome$$romefrontend$core$server$Server_ts$default.emitServerLog (project-rome/@romefrontend/core/server/Server.ts:321:15)
  at Object.write (project-rome/@romefrontend/core/server/Server.ts:248:10)
  at ___R$project$rome$$romefrontend$core$common$utils$Logger_ts$default.writeSpecific (project-rome/@romefrontend/cli-reporter/Reporter.ts:737:9)
  at ___R$project$rome$$romefrontend$core$common$utils$Logger_ts$default.logOneRaw (project-rome/@romefrontend/cli-reporter/Reporter.ts:927:7)
  at ___R$project$rome$$romefrontend$core$common$utils$Logger_ts$default.logOne (project-rome/@romefrontend/cli-reporter/Reporter.ts:898:8)
  at ___R$project$rome$$romefrontend$core$common$utils$Logger_ts$default.logAllWithCategory (project-rome/@romefrontend/cli-reporter/Reporter.ts:973:8)
  at ___R$project$rome$$romefrontend$core$common$utils$Logger_ts$default.info (project-rome/@romefrontend/cli-reporter/Reporter.ts:1007:7)
  at Object.onSendMessage (project-rome/@romefrontend/core/server/WorkerManager.ts:253:24)
  at ___R$project$rome$$romefrontend$core$common$bridges$WorkerBridge_ts$default.sendMessage (project-rome/@romefrontend/events/Bridge.ts:359:8)
  at sendMessage (project-rome/@romefrontend/events/BridgeEvent.ts:201:16)
  at new Promise
  at ___R$project$rome$$romefrontend$events$BridgeEvent_ts$default.call (project-rome/@romefrontend/events/BridgeEvent.ts:161:16)
  at call (project-rome/@romefrontend/core/server/ServerRequest.ts:1019:32)
  at ___R$project$rome$$romefrontend$core$server$ServerRequest_ts$default.wrapRequestDiagnostic (project-rome/@romefrontend/core/server/ServerRequest.ts:867:24)
  at global.runMicrotasks
  at process.processTicksAndRejections (internal/process/task_queues.js:85:4) generated source location
  at ___R$project$rome$$romefrontend$core$server$ServerRequest_ts$default.requestWorkerLint (project-rome/@romefrontend/core/server/ServerRequest.ts:1016:14)
  at Function.allowMissing (project-rome/@romefrontend/core/common/FileNotFound.ts:44:11)
  at <anonymous> (project-rome/@romefrontend/core/server/linter/Linter.ts:219:15)
  at next (project-rome/@romefrontend/core/server/WorkerQueue.ts:93:4)
  at next (project-rome/@romefrontend/core/server/WorkerQueue.ts:95:3)
  at next (project-rome/@romefrontend/core/server/WorkerQueue.ts:95:3)
  at next (project-rome/@romefrontend/core/server/WorkerQueue.ts:95:3)
  at next (project-rome/@romefrontend/core/server/WorkerQueue.ts:95:3)
  at next (project-rome/@romefrontend/core/server/WorkerQueue.ts:95:3)
  at next (project-rome/@romefrontend/core/server/WorkerQueue.ts:95:3)
  at next (project-rome/@romefrontend/core/server/WorkerQueue.ts:95:3)
  at Function.all
  at ___R$project$rome$$romefrontend$core$server$WorkerQueue_ts$default.processWorker (project-rome/@romefrontend/core/server/WorkerQueue.ts:104:3)]
[2020-07-21T19:58:08.705Z] [server 59485] ✖ Fatal error occurred: Error: Range end for line index 21
                                            is before the start. end(1) < start(7).
                                            Line content: ""
                                              at
                                            ___R$project$rome$$romefrontend$cli$layout$grid$Grid_ts$
                                            default.setRange
                                            (project-rome/@romefrontend/cli-layout/grid/Grid.ts:584:
                                            9)
```
</details>

**Comment by sebmck** [comment]
I think there might be something weird going on with line wrapping. In `cli-layout` when we're writing text we register the text ranges with the tags we're inside of so we can properly format the final output. Pretty sure we wont ever color the output in that environment though so you should be able to safely comment out that `throw`.

**Comment by yassere** [comment]
This was fixed at some point, possibly when `ClientLogsLevel` was added. The `--logs all` and `--logs error` flags both work with the `lsp` command without crashing.
